#!/bin/sh

#DEBHELPER#

ui=06univention-openvpn-master-uninstall.uinst

if [ "$1" = "remove" ]; then
	ucr unset \
		ucs/web/overview/entries/service/openvpn4ucs_dl/description/de \
		ucs/web/overview/entries/service/openvpn4ucs_dl/description \
		ucs/web/overview/entries/service/openvpn4ucs_dl/label/de \
		ucs/web/overview/entries/service/openvpn4ucs_dl/label \
		ucs/web/overview/entries/service/openvpn4ucs_dl/link

	. /usr/share/univention-lib/base.sh
	call_unjoinscript "$ui"
	invoke-rc.d univention-directory-listener restart
fi

exit 0
