#!/bin/sh

#DEBHELPER#

ucr unset ucs/web/overview/entries/service/openvpn4ucs_dl/description/de
ucr unset ucs/web/overview/entries/service/openvpn4ucs_dl/description
ucr unset ucs/web/overview/entries/service/openvpn4ucs_dl/label/de
ucr unset ucs/web/overview/entries/service/openvpn4ucs_dl/label
ucr unset ucs/web/overview/entries/service/openvpn4ucs_dl/link

ui=06univention-openvpn-master-uninstall.uinst

if [ "$1" = "remove" ]; then
	. /usr/share/univention-lib/base.sh
	call_unjoinscript "$ui"
	invoke-rc.d univention-directory-listener restart
fi

exit 0
