#!/bin/sh

#DEBHELPER#

ucr unset ucs/web/overview/entries/service/openvpn4ucs/description/de
ucr unset ucs/web/overview/entries/service/openvpn4ucs/description
ucr unset ucs/web/overview/entries/service/openvpn4ucs/label/de
ucr unset ucs/web/overview/entries/service/openvpn4ucs/label
ucr unset ucs/web/overview/entries/service/openvpn4ucs/link

ui=06univention-openvpn-server-uninstall.uinst

if [ "$1" = "remove" ]; then
	. /usr/share/univention-lib/base.sh
	call_unjoinscript "$ui"
	invoke-rc.d univention-directory-listener restart
fi

exit 0
