#!/bin/sh

#DEBHELPER#

ui=/usr/lib/univention-install/06univention-openvpn-master-uninstall.uinst

if [ "$1" = "configure" ]; then
	[ -e "$ui" ] && rm "$ui"
	invoke-rc.d univention-directory-listener restart
fi

ucr set ucs/web/overview/entries/service/openvpn4ucs_dl/description='OpenVPN4UCS ready2go packages'
ucr set ucs/web/overview/entries/service/openvpn4ucs_dl/description/de='OpenVPN4UCS ready2go Pakete'
ucr set ucs/web/overview/entries/service/openvpn4ucs_dl/label='OpenVPN4UCS ready2go packages'
ucr set ucs/web/overview/entries/service/openvpn4ucs_dl/label/de='OpenVPN4UCS ready2go Pakete'
ucr set ucs/web/overview/entries/service/openvpn4ucs_dl/link='/download'

. /usr/share/univention-lib/base.sh
call_joinscript 94univention-openvpn-master.inst

exit 0
