#!/bin/sh

#DEBHELPER#

if [ "$1" = "configure" ]; then
	rdy2gobas="/var/www/readytogo"
	templates=/usr/lib/openvpn-int/templates

	mkdir -p "${rdy2gobas}"

	cat > "${rdy2gobas}/.htaccess" <<-ENDOFHTACCESS
	ErrorDocument 404 /readytogo/notfound.html
	ENDOFHTACCESS

	cp ${templates}/download.head "${rdy2gobas}/notfound.html"
	echo "<p>This page does not exist. Please talk to your VPN admin who should consider a license issue.</p>" >> "${rdy2gobas}/notfound.html"
	cat ${templates}/download.tail >> "${rdy2gobas}/notfound.html"


	cat > /etc/apache2/sites-available/openvpn4ucs2.conf <<-ENDOFSITECFG
	<Location /readytogo>
	    Options -Indexes
	</Location>
	ENDOFSITECFG

	chmod 0600 /etc/apache2/sites-available/openvpn4ucs2.conf


	for dir in /var/www/readytogo/*/
	do
	    sed -i "/AuthLDAPBindPassword/c\AuthLDAPBindPassword ${pw}" $dir.htaccess
	    sed -i "/AuthLDAPBindDN/c\AuthLDAPBindDN \"uid=$name,cn=users,$ldap_base\"" $dir.htaccess
	done

	if [ $(ucr get server/role) = domaincontroller_master ]; then
	    ucr set \
		ucs/web/overview/entries/service/openvpn4ucs_dl/description='OpenVPN4UCS - ready2go packages' \
		ucs/web/overview/entries/service/openvpn4ucs_dl/description/de='OpenVPN4UCS - ready2go Pakete' \
		ucs/web/overview/entries/service/openvpn4ucs_dl/label='OpenVPN4UCS - ready2go packages' \
		ucs/web/overview/entries/service/openvpn4ucs_dl/label/de='OpenVPN4UCS - ready2go Pakete' \
		ucs/web/overview/entries/service/openvpn4ucs_dl/icon='download/openvpn4ucs.svg' \
		ucs/web/overview/entries/service/openvpn4ucs_dl/link='/download'
	else
	    ucr set \
		ucs/web/overview/entries/service/openvpn4ucs_ndl/description='OpenVPN4UCS - new ready2go packages' \
		ucs/web/overview/entries/service/openvpn4ucs_ndl/description/de='OpenVPN4UCS - neue ready2go Pakete' \
		ucs/web/overview/entries/service/openvpn4ucs_ndl/label='OpenVPN4UCS - new ready2go packages' \
		ucs/web/overview/entries/service/openvpn4ucs_ndl/label/de='OpenVPN4UCS - neue ready2go Pakete' \
		ucs/web/overview/entries/service/openvpn4ucs_ndl/icon='download/openvpn4ucs.svg' \
		ucs/web/overview/entries/service/openvpn4ucs_ndl/link='/download'
	fi

	a2ensite openvpn4ucs2

	/etc/init.d/apache2 restart
fi

exit 0
