63openvpn-sitetosite.acl usr/lib/openvpn-int/misc
univention-openvpn.py usr/lib/openvpn-int/misc
univention-openvpn-schema.py usr/lib/openvpn-int/misc
openvpn-master.py usr/lib/univention-directory-listener/system
openvpn-master2.py usr/lib/univention-directory-listener/system
94univention-openvpn-master.inst usr/lib/univention-install
06univention-openvpn-master-uninstall.uinst usr/lib/univention-uninstall
cleanup-dmp /usr/lib/openvpn-int
