#!/bin/sh

#DEBHELPER#

ui=06univention-openvpn-server-uninstall.uinst

if [ "$1" = "remove" ]; then
	ucr unset \
		ucs/web/overview/entries/service/openvpn4ucs/description/de \
		ucs/web/overview/entries/service/openvpn4ucs/description \
		ucs/web/overview/entries/service/openvpn4ucs/label/de \
		ucs/web/overview/entries/service/openvpn4ucs/label \
		ucs/web/overview/entries/service/openvpn4ucs/icon \
		ucs/web/overview/entries/service/openvpn4ucs/link

	. /usr/share/univention-lib/base.sh
	call_unjoinscript "$ui"
	invoke-rc.d univention-directory-listener restart
fi

exit 0
