#!/bin/sh

# create /etc/apache2/sites-available/openvpn4ucs

eval "$(ucr shell)"
pw=$(cat /etc/ldapper-s.secret)
cat > /etc/apache2/sites-available/openvpn4ucs<<-ENDOFSITECFG
<Location /display_users>
    AuthBasicProvider ldap
    AuthType Basic
    AuthName "Please login as a VPN Admin"
    AuthzLDAPAuthoritative off
    AuthLDAPURL "ldap://$ldap_server_name:$ldap_server_port/$ldap_base?uid"
    AuthLDAPBindDN "uid=ldapper-s-$hostname,cn=users,$ldap_base"
    AuthLDAPBindPassword $pw
    Require ldap-group cn=VPN Admins,cn=groups,$ldap_base
</Location>

ProxyPass /display_users/cmd/ http://localhost:38081/display_users/cmd/
ProxyPassReverse /display_users/cmd/ http://localhost:38081/display_users/cmd/

ENDOFSITECFG

chmod 0600 /etc/apache2/sites-available/openvpn4ucs
