#!/bin/bash

CADIR=/tmp/o4uCA

if [ -d ${CADIR} ]; then
    echo "NOTICE: ${CADIR} already exists. Skipping CA setup."
    exit 0
fi

umask 027
mkdir -p ${CADIR}/issued
date +%y%m%d000000Z > ${CADIR}/enddate

openssl req -x509 -days 3652 -nodes -newkey rsa:2048 -keyout ${CADIR}/ca.key -out ${CADIR}/ca.crt -config <(cat<<_ENDOFCONFIG_
[req]
prompt			= no
default_md		= sha256
x509_extensions		= v3_ca
distinguished_name	= dn
[v3_ca]
subjectKeyIdentifier	= hash
authorityKeyIdentifier	= keyid:always,issuer
basicConstraints	= CA:true
nsCertType		= sslCA
[dn]
CN			= $(hostname) OpenVPN4UCS CA
_ENDOFCONFIG_
)

: > ${CADIR}/db
openssl rand -hex 8 > ${CADIR}/serial

cat > ${CADIR}/config <<_ENDOFCONFIG_
[o4uCA]
dir		= ${CADIR}		# Where everything is kept
database	= \$dir/db		# database index file.
new_certs_dir	= \$dir/issued		# -outdir 
certificate	= \$dir/ca.crt	 	# The CA certificate (-cert)
private_key	= \$dir/ca.key		# The private key (-key)
serial		= \$dir/serial 		# The current serial number
x509_extensions	= usr_cert		# The extentions to add to the cert
name_opt 	= ca_default		# Subject Name options
cert_opt 	= ca_default		# Certificate field options
default_enddate	= $(date +%y%m%d000000Z)	# how long to certify for
default_crl_days= 30			# how long before next CRL
default_md	= sha256		# use public key default MD (-md)
#preserve	= no			# keep passed DN ordering
policy		= cn_only

[cn_only]
commonName	= supplied

[usr_cert]
nsCertType		= client
subjectKeyIdentifier	= hash
authorityKeyIdentifier	= keyid,issuer

[srv_cert]
nsCertType		= server
subjectKeyIdentifier	= hash
authorityKeyIdentifier	= keyid,issuer
_ENDOFCONFIG_

VPN=/tmp
openssl ca -config ${CADIR}.config -name o4uCA -out ${VPN}/server.crt -notext -extensions srv_cert -in <(
openssl req -nodes -newkey rsa:2048 -keyout ${VPN}/server.key -config <(
cat <<_ENDOFCONFIG_
[req]
prompt             = no
default_md         = sha256
distinguished_name = dn
[dn]
CN = $(hostname)
_ENDOFCONFIG_
))

openssl ca -config ${CADIR}/config -name o4uCA -gencrl -out ${CADIR}/crl.pem
