#!/bin/bash

CADIR=/etc/openvpn/o4uCA
USERS=${CADIR}/users

if [ -z $1 ]; then
	echo "usage: $0 <username>" >&2
	exit 1
fi

if [ -d ${USERS}/$1 ]; then
	echo "ERROR: ${USERS}/$1 already exists" >&2
	exit 1
fi

umask 027
mkdir ${USERS}/"$1"

openssl ca -config ${CADIR}/config -name o4uCA -batch -notext -out ${USERS}/"$1"/cert.pem -in <(
openssl req -nodes -newkey rsa:2048 -keyout ${USERS}/"$1"/private.key -config <(
cat <<_ENDOFCONFIG_
[req]
prompt			= no
default_md		= sha256
distinguished_name	= dn
[dn]
CN			= $1
_ENDOFCONFIG_
))
