#!/bin/bash

if [ $# -ne 3 ]; then
    echo "remove-bundle: argument error" >&2
    echo "usage: remove-bundle <uid> <home> <server>" >&2
    exit 1
fi

uid=$1
home=$2
server=$3

# delete readytogo packages
umask 037
rdy2gobas="/var/www/readytogo"
readytogo="${rdy2gobas}/${uid}/"
rm -r "${readytogo}"

if [ -d "$home" ]; then
    umask 077
    bundle="${home}/openvpn-${server}-${uid}.zip"
    rm ${bundle}
fi

exit 0
