#!/bin/bash

if [ $# -ne 3 ]; then
    echo "remove-bundle: argument error" >&2
    echo "usage: remove-bundle <uid> <server>" >&2
    exit 1
fi

uid=$1
server=$2

# delete readytogo packages
umask 037
rdy2gobas="/var/www/readytogo"
readytogo="${rdy2gobas}/${uid}/"
rm -r "${readytogo}"

exit 0
